name: POI API CI Pipeline

on:
  push:
    paths:
    - 'apis/poi/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/poi/**'
      
jobs: 
   
  build:
    env: 
      working-directory: ./apis/poi

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
      
    - name: Build
      run: dotnet build --no-restore 
      working-directory: ${{env.working-directory}}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.working-directory}}
      
    - name: Create Bug for Failed Build
      uses: stefanstranger/azuredevops-bug-action@1.1
      if: failure()
      with:
        OrganizationName: "hacker1dn2"
        PAT: "PAT"
        ProjectName: "TripViewer"
        AreaPath: "TripViewer"
        IterationPath: "TripViewer"
        GithubToken: "GithubToken"
        WorkflowFileName: "poi-api-ci-pipeline.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_ACCESS_TOKEN }}
        GithubToken: ${{ secrets.GITHUB_TOKEN}}
      
