name: POI API CI/CD Pipeline

on:
  push:
    paths:
    - 'apis/poi/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/poi/**'
      
jobs: 
  build:
    env: 
      working-directory: ./apis/poi
      acr-name: openhackfwl15lz6acr

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
      
    - name: Build
      run: dotnet build --no-restore 
      working-directory: ${{env.working-directory}}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.working-directory}}
      
    - name: Create Bug for Failed Build
      uses: stefanstranger/azuredevops-bug-action@1.1
      if: failure()
      with:
        OrganizationName: "hacker1dn2"
        PAT: "PAT"
        ProjectName: "TripViewer"
        AreaPath: "TripViewer"
        IterationPath: "TripViewer"
        GithubToken: "GithubToken"
        WorkflowFileName: "poi-api-ci-pipeline.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_ACCESS_TOKEN }}
        GithubToken: ${{ secrets.GITHUB_TOKEN}}
    
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_APP_LOGIN }}'

    - name: Build/Push Docker Container
      if: github.ref == 'refs/heads/master'
      run: az acr build --image "devopsoh/api-poi:${{ env.GITHUB_RUN_NUMBER }}" --registry ${{ env.acr-name }} --file Dockerfile .
      working-directory: ${{ env.working-directory }}/web
      
