name: POI API CI Pipeline

on:
  workflow_dispatch:
  push:
    paths:
    - 'apis/poi/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/poi/**'
      
jobs: 
   
  build:
    env: 
      working-directory: ./apis/poi

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.5
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
      
    - name: Build
      run: dotnet build --no-restore 
      working-directory: ${{env.working-directory}}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.working-directory}}
      
